version: "3.8"

services:

  accounts:
    image: dibbydon/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - dibbydon-network
    
  loans:
    image: dibbydon/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - dibbydon-network
    
  cards:
    image: dibbydon/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - dibbydon-network
    
networks:
  dibbydon-network: